
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# http_archive(
#     name = "rules_experimental_android",
#     url = "https://github.com/jin/rules_experimental_android/archive/master.zip",
#     strip_prefix = "rules_experimental_android-master",
# )

# local_repository(
#     name = "rules_experimental_android",
#     path = "/Users/jingwen/code/rules_experimental_android",
# )

RULES_JVM_EXTERNAL_TAG = "2.6.1"
RULES_JVM_EXTERNAL_SHA = "45203b89aaf8b266440c6b33f1678f516a85b3e22552364e7ce6f7c0d7bdc772"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:specs.bzl", "maven")

load("@rules_jvm_external//:defs.bzl", "maven_install")
maven_install(
    name = "maven",
    artifacts = [
        # app:implementation
        "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21",
        "androidx.appcompat:appcompat:1.0.2",
        "androidx.constraintlayout:constraintlayout:1.1.3",
        "androidx.lifecycle:lifecycle-extensions:2.1.0-alpha03",
        # app:annotationProcessor
        maven.artifact("androidx.databinding", "databinding-compiler", "3.3.2", neverlink = True),
        # app:api
        "androidx.databinding:databinding-common:3.3.2",
        "androidx.databinding:databinding-runtime:3.3.2",
        "androidx.databinding:databinding-adapters:3.3.2",
    ],
    repositories = [
        "https://maven.google.com",
        "https://jcenter.bintray.com",
        "https://repo1.maven.org/maven2",
    ],
)

# bind(
#     name = "databinding_annotation_processor",
#     actual = "//:androidx_databinding_databinding_compiler_plugin"
# )

android_sdk_repository(name = "androidsdk")
RULES_KOTLIN_VERSION = "ecc895796f503f43a2f2fb2a120ee54fa597cd34"
http_archive(
    name = "io_bazel_rules_kotlin",
    strip_prefix = "rules_kotlin-%s" % RULES_KOTLIN_VERSION,
    url = "https://github.com/cgruber/rules_kotlin/archive/%s.tar.gz" % RULES_KOTLIN_VERSION,
    sha256 = "",
)
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories()
kt_register_toolchains()
